### ISSUE TITLE
Solution does not work

### ISSUE THREAD

**Issue by haroonkhan9426** [feinstein/firebase_user_stream#1]
Here I tried this solution:
Previous photoUrl was 'foo' and I was updating it to 'bar'

```dart
final user = await _auth.currentUser();
print('Before update: ${user.displayName}, ${user.photoUrl}');
user.updateProfile(updatedInfo);
await user.reload();
    FirebaseUserReloader.onUserReloaded.listen((user) {
      print('User Reloaded: ${user.photoUrl}');
    });
FirebaseUserReloader.reloadCurrentUser();
final newUser = await FirebaseAuth.instance.currentUser();
print('After update: ${newUser.displayName}, ${newUser.photoUrl}');
final newestUser = await FirebaseAuth.instance.currentUser();
print('After update: ${newestUser.displayName}, ${newestUser.photoUrl}');
```

And here is the result:
>I/flutter ( 5492): Before update: test20, foo
>I/flutter ( 5492): After update: test20, foo
>I/flutter ( 5492): User Reloaded: foo
>I/flutter ( 5492): User Reloaded: foo
>I/flutter ( 5492): User Reloaded: foo
>I/flutter ( 5492): User Reloaded: foo
>I/flutter ( 5492): After update: test20, foo

**Comment by feinstein** [comment]
1. I reformatted your issue, as it's clearer to read, take a look at the modifications that I did, so you can use them in the future.

2. Try awaiting the update and tell me if it works, like this:

```dart
await user.updateProfile(updatedInfo);
```

**Comment by haroonkhan9426** [comment]
> 1. I reformatted your issue, as it's clearer to read, take a look at the modifications that I did, so you can use them in the future.
> 2. Try awaiting the update and tell me if it works, like this:
> 
> ```dart
> await user.updateProfile(updatedInfo);
> ```
Thank you so much. 
Issue resolved and got your point as well plus the actual purpose of this plugin.

Thanks for all.
