### ISSUE TITLE
Please update for latest firebase_auth

### ISSUE THREAD

**Issue by awhitford** [feinstein/firebase_user_stream#4]
`firebase_auth` was recently upgraded with some significant changes:
 * https://pub.dev/packages/firebase_auth/changelog

**Comment by feinstein** [comment]
I was waiting these changes to go stable in order to update the library.

I am wondering if this library is still relevant since now `firebase_auth` has `userChanges()`. I would like hear your thoughts as a user.

**Comment by awhitford** [comment]
Oh, good point...  I can try swapping your library for the new `userChanges()` and see if that captures the key issues.

**Comment by feinstein** [comment]
Please let me know how it goes.

**Comment by feinstein** [comment]
If you want to compare, try the  `1.1.0-alpha` I just released with the `firebase_auth` v0.18.0 updates.

**Comment by awhitford** [comment]
Sorry I never commented back on this, but it does appear that I was able to remove this dependency and use _out of the box_ functionality now.  (I haven't yet cut a fresh release of my apps, which is what gave me pause, but so far, so good.)

**Comment by feinstein** [comment]
Yeah, this was my experience too.

**Comment by tomasmisutka** [comment]
hello, new update of firebase_auth and firebase_core released, and your package is currently not compatible... could you fix that please ? thank you !

**Comment by feinstein** [comment]
Hi @tomasmisutka. If you look at the README, this package has been deprecated, as Firebase now has `userChanges()`.

**Comment by tomasmisutka** [comment]
yes, you are right, thank you very much, i am so sorry :)
